# CompuLab Devices BSP

To get the BSP you need to have `repo` installed and use it as:

## Install the `repo` utility:

[source,console]
$: mkdir ~/bin
$: curl http://commondatastorage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
$: chmod a+x ~/bin/repo

## Select an available bsp version name: `krogoth/morty/pyro`
[source,console]
$: export BSP=krogoth
or
$: export BSP=morty
or
$: export BSP=pyro

## Download the BSP source:
[source,console]
$: PATH=${PATH}:~/bin
$: mkdir compulab-bsp
$: cd compulab-bsp
$: repo init -u https://github.com/compulab-yokneam/compulab-bsp -b ${BSP}
$: repo sync

At the end of the commands you have every metadata you need to start work with.
You can use any directory to host your build. The source code is checked out at `compulab-bsp/sources`.

## Build Procedure
### Select an available machine: `cm-fx6-evk/cl-som-imx6`
[source,console]
$: export MACHINE=cm-fx6-evk
or
$: export MACHINE=cl-som-imx6

### Select an available image: `compulab-eval-image/compulab-eval-image-xfce`
[source,console]
$: export IMAGE=compulab-eval-image
or
$: export IMAGE=compulab-eval-image-xfce

### Setup Build Environment
[source,console]
$: source ./setup-environment build

### Build Evaluation Image
[source,console]
$: bitbake ${IMAGE}

### Build kernel only

[source,console]
$: bitbake linux-compulab

### Build U-Boot only

[source,console]
$: bitbake u-boot-compulab

## https://github.com/compulab-yokneam/Documentation/tree/master/common/post-build#meta-compulab-post-build-instructions[Post Build Instructions]
