# CompuLab Devices BSP

To get the BSP you need to have `repo` installed and use it as:

## Install the `repo` utility:

[source,console]
$: mkdir ~/bin
$: curl http://commondatastorage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
$: chmod a+x ~/bin/repo

## Download the BSP source:

[source,console]
$: PATH=${PATH}:~/bin
$: mkdir compulab-bsp
$: cd compulab-bsp
$: repo init -u https://github.com/compulab-yokneam/compulab-bsp -b ${BSP}
$: repo sync

At the end of the commands you have every metadata you need to start work with.
You can use any directory to host your build. The source code is checked out at `compulab-bsp/sources`.

## Build Procedure
### Select an available machine: cm-fx6-evk/cl-som-imx6
[source,console]
$: export MACHINE=cm-fx6-evk
or
$: export MACHINE=cl-som-imx6

### Select an available image: compulab-eval-image/compulab-eval-image-xfce
[source,console]
$: export IMAGE=compulab-eval-image
or
$: export IMAGE=compulab-eval-image-xfce

### Setup Build Environment
[source,console]
$: source ./setup-environment build

### Build Evaluation Image
[source,console]
$: bitbake ${IMAGE}

### Build kernel only

[source,console]
$: bitbake linux-compulab

### Build U-Boot only

[source,console]
$: bitbake u-boot-compulab

## How to Deploy:
[%hardbreaks]
To deploy the image file to an sdcard, issue this command. 
Assuming the sdcard device file is *_/dev/sdg_*

[source,console]
$: xz -dc tmp/deploy/images/${MACHINE}/${IMAGE}-${MACHINE}.sdcard.xz | sudo dd of=/dev/sdg

## How to Evaluate:
. Insert the sd-card into the SB-FX6 P6 slot
. Power up the device
. Stop in U-Boot
. Issue:
[%hardbreaks]
[source,console]
# env default -a
# savenv
# reset
. Let the device boot up
. Evaluate this Yocto Release

## How to Deploy on an internal media.
`compulab-eval-image` and `compulab-eval-image-xfce` come with a tool that allows cloning the boot media. +
Detailed information at: https://github.com/compulab-yokneam/Documentation/blob/master/cl-deploy/README.adoc#compulab-deployment-tool[CompuLab Deployment Tool]
