# meta-compulab 

Supported CompuLab Machines: `cm-fx6-evk, cl-som-imx6ul, cl-som-imx7, cl-som-imx6`

## How To

### https://github.com/compulab-yokneam/Documentation/blob/master/yocto-build-environmet/README.adoc#before-the-start[Before The Start]

### Prepare BSP Environment
#### Select an available NXP branch: `imx-4.1-krogoth/imx-morty`
[source,console]
$: export IMX_BRANCH=imx-4.1-krogoth
or
$: export IMX_BRANCH=imx-morty

#### `imx-morty` known issue

* The buid fails with an error `imx-gpu-viv-1_5.0.11.p8.7-hfp-r0 do_fetch: Error ...` + 
https://community.nxp.com/thread/452335
* Work around: + 
In order to evaluate Yocto Morty follow this instructions: https://github.com/compulab-yokneam/Documentation/tree/master/compulab-bsp#compulab-devices-bsp[CompuLab Morty BSP]

#### Download the NXP BSP source:
[source,console]
$: repo init -u git://git.freescale.com/imx/fsl-arm-yocto-bsp.git -b ${IMX_BRANCH}
$: repo sync

#### `imx-4.1-krogoth` issues
* chromium gcc-6 fix
[source,console]
$: git -C sources/meta-browser checkout 393d2aa15da21ffa532c3cd77d8cb91de997cd31
* https://github.com/openembedded/openembedded-core/tree/master/meta/recipes-support/lzop[oe-core: lzop gcc-6 patch]
* http://lists.openembedded.org/pipermail/openembedded-core/2017-January/132040.html[oe-core: rootfs build failure]

#### Clone `meta-compulab` layer:
[source,console]
$: git clone -b devel https://github.com/compulab-yokneam/meta-compulab sources/meta-compulab

### Build Procedure
#### Select an available machine: `cm-fx6-evk/cl-som-imx6ul/cl-som-imx7/cl-som-imx6`
[source,console]
$: export MACHINE=cm-fx6-evk
or
$: export MACHINE=cl-som-imx6ul
or
$: export MACHINE=cl-som-imx7
or
$: export MACHINE=cl-som-imx6

#### Select an available distro: `x11/fb/xwayland/wayland`
[source,console]
$: export DISTRO=fsl-imx-x11
or
$: export DISTRO=fsl-imx-fb
or
$: export DISTRO=fsl-imx-xwayland
or
$: export DISTRO=fsl-imx-wayland

#### Create Build Environment
[source,console]
$: source fsl-setup-release.sh -b build-${MACHINE}-${DISTRO}

#### Pre-Build Steps
* Add the `meta-compulab` location to the conf/bblayers.conf

[source,console]
$: [[ -f conf/bblayers.conf ]] && (sed -i '$aBBLAYERS += " ${BSPDIR}/sources/meta-compulab "' conf/bblayers.conf) || echo "Warning: Invalid Build Directory"

* Add the `meta-xfce` location to the conf/bblayers.conf

[source,console]
$: [[ -f conf/bblayers.conf ]] && (sed -i '$aBBLAYERS += " ${BSPDIR}/sources/meta-openembedded/meta-xfce "' conf/bblayers.conf) || echo "Warning: Invalid Build Directory"

WARNING: Stop Here if the warning shows up

* Add the second packaging option to the conf/local.conf

[source,console]
$: [[ -f conf/local.conf ]] && sed -i '/PACKAGE_CLASSES/ a PACKAGE_CLASSES += " package_deb"' conf/local.conf || echo "Warning: Invalid Build Directory"

#### Build Instruction
##### Select an available image: `fsl-image-gui/fsl-image-qt5/compulab-eval-image/compulab-eval-image-xfce`
[source,console]
$: export IMAGE=fsl-image-gui
or
$: export IMAGE=fsl-image-qt5
or
$: export IMAGE=compulab-eval-image
or
$: export IMAGE=compulab-eval-image-xfce

##### Build Evaluation Image
[source,console]
$: bitbake ${IMAGE}

##### Build kernel only
[source,console]
$: bitbake linux-compulab

##### Build U-Boot only
[source,console]
$: bitbake u-boot-compulab

## https://github.com/compulab-yokneam/Documentation/tree/master/common/post-build#post-build-instructions[Post Build Instructions]
