# meta-compulab 

Supported CompuLab Machines: `cm-fx6-evk, cl-som-imx6ul, cl-som-imx7, cl-som-imx6`

## How To

### https://github.com/compulab-yokneam/Documentation/blob/master/yocto-build-environmet/README.adoc#before-the-start[Before The Start]

### Prepare BSP Environment
#### Select an available NXP branch: `imx-4.1-krogoth/imx-morty`
[source,console]
$: export IMX_BRANCH=imx-4.1-krogoth
or
$: export IMX_BRANCH=imx-morty

#### Download the NXP BSP source:
[source,console]
$: repo init -u git://git.freescale.com/imx/fsl-arm-yocto-bsp.git -b ${IMX_BRANCH}
$: repo sync

#### Clone `meta-compulab` layer:
[source,console]
$: git clone -b devel https://github.com/compulab-yokneam/meta-compulab sources/meta-compulab

#### `imx-4.1-krogoth` issues
NOTE: These fixes must be applied `only` if the build ran into them

* chromium gcc-6 fix
[source,console]
$: git -C sources/meta-browser checkout 393d2aa15da21ffa532c3cd77d8cb91de997cd31

* `lzop gcc-6` fix
[source,console]
$: git -C sources/meta-compulab cherry-pick 8ede5fef9575246480af94808d1f60658aaff6a3

** https://github.com/openembedded/openembedded-core/tree/master/meta/recipes-support/lzop[patch source/info]

* `No real function for mknod` fix
[source,console]
$: git -C sources/meta-compulab cherry-pick d44a09a8be848a56c7670c4b416382b41e2542d3

** https://lists.yoctoproject.org/pipermail/yocto/2016-October/032240.html[patch source/info]

* `rootfs build failure` fix/workaround
** http://lists.openembedded.org/pipermail/openembedded-core/2017-January/132040.html

### Build Procedure
#### Select an available machine: `cm-fx6-evk/cl-som-imx6ul/cl-som-imx7/cl-som-imx6`
[source,console]
$: export MACHINE=cm-fx6-evk
or
$: export MACHINE=cl-som-imx6ul
or
$: export MACHINE=cl-som-imx7
or
$: export MACHINE=cl-som-imx6

#### Select an available distro: `x11/fb/xwayland/wayland`
[source,console]
$: export DISTRO=fsl-imx-x11
or
$: export DISTRO=fsl-imx-fb
or
$: export DISTRO=fsl-imx-xwayland
or
$: export DISTRO=fsl-imx-wayland

#### Create Build Environment
[source,console]
$: source fsl-setup-release.sh -b build-${MACHINE}-${DISTRO}

#### Common Pre-Build Steps
* Add the `meta-compulab` location to the conf/bblayers.conf

[source,console]
$: [[ -f conf/bblayers.conf ]] && (sed -i '$aBBLAYERS += " ${BSPDIR}/sources/meta-compulab "' conf/bblayers.conf) || echo "Warning: Invalid Build Directory"

* Add the `meta-xfce` location to the conf/bblayers.conf

[source,console]
$: [[ -f conf/bblayers.conf ]] && (sed -i '$aBBLAYERS += " ${BSPDIR}/sources/meta-openembedded/meta-xfce "' conf/bblayers.conf) || echo "Warning: Invalid Build Directory"

WARNING: Stop Here if the warning shows up

* Add `CompuLab Deployment Tool` into the image install list

[source,console]
$: [[ -f conf/local.conf ]] && sed -i '$ a CORE_IMAGE_EXTRA_INSTALL += " cl-deploy"' conf/local.conf || echo "Warning: Invalid Build Directory"

* Add the second packaging option to the conf/local.conf

[source,console]
$: [[ -f conf/local.conf ]] && sed -i '/PACKAGE_CLASSES/ a PACKAGE_CLASSES += " package_deb"' conf/local.conf || echo "Warning: Invalid Build Directory"

#### `cl-som-imx6ul` Pre-Build Steps
NOTE: `cl-som-imx6ul` machines make use of a `TI Wilink8` chip.
This device requires a configuration tool provided by `meta-ti` layer.

* Clone `meta-ti` layer
[source,console]
$: git clone git://git.yoctoproject.org/meta-ti ../sources/meta-ti

* Add the `meta-ti` location to the conf/bblayers.conf for `cl-som-imx6ul` only

[source,console]
$: [[ -f conf/bblayers.conf ]] && (sed -i '$aBBLAYERS += " ${BSPDIR}/sources/meta-ti "' conf/bblayers.conf) || echo "Warning: Invalid Build Directory"

* Add `User Mode initialisation Manager Daemon` into the image install list for `cl-som-imx6ul`

[source,console]
$: [[ -f conf/local.conf ]] && sed -i '$ a CORE_IMAGE_EXTRA_INSTALL += " uim"' conf/local.conf || echo "Warning: Invalid Build Directory"

#### Build Instruction
##### Select an available image: `fsl-image-gui/fsl-image-qt5/compulab-eval-image/compulab-eval-image-xfce`
[source,console]
$: export IMAGE=fsl-image-gui
or
$: export IMAGE=fsl-image-qt5
or
$: export IMAGE=compulab-eval-image
or
$: export IMAGE=compulab-eval-image-xfce

##### Build Evaluation Image
[source,console]
$: bitbake ${IMAGE}

##### Build kernel only
[source,console]
$: bitbake linux-compulab

##### Build U-Boot only
[source,console]
$: bitbake u-boot-compulab

## https://github.com/compulab-yokneam/Documentation/tree/master/common/post-build#post-build-instructions[Post Build Instructions]
