# meta-compulab 

Supported CompuLab Machines: `cm-fx6-evk, cl-som-imx6ul, cl-som-imx7, cl-som-imx6`

## How To

### https://github.com/compulab-yokneam/Documentation/blob/master/yocto-build-environmet/README.adoc#before-the-start[Before The Start]

### Prepare BSP Environment
#### Select an available NXP branch: `imx-4.1-krogoth/imx-morty`
[source,console]
$: export IMX_BRANCH=imx-4.1-krogoth
or
$: export IMX_BRANCH=imx-morty

#### Download the NXP BSP source:
[source,console]
$: repo init -u git://git.freescale.com/imx/fsl-arm-yocto-bsp.git -b ${IMX_BRANCH}
$: repo sync

#### Clone `meta-compulab` layer:
[source,console]
$: git clone -b devel https://github.com/compulab-yokneam/meta-compulab sources/meta-compulab

#### `imx-4.1-krogoth` fixes
NOTE: These fixes must be applied `only` if the build ran into them

* `chromium gcc-6`
[source,console]
$: git -C sources/meta-browser checkout 393d2aa15da21ffa532c3cd77d8cb91de997cd31

* `lzop gcc-6`
[source,console]
$: git -C sources/meta-compulab cherry-pick 8ede5fef9575246480af94808d1f60658aaff6a3

* `No real function for mknod`
[source,console]
$: git -C sources/meta-compulab cherry-pick d44a09a8be848a56c7670c4b416382b41e2542d3

* `mesa fetch issue`
[source,console]
$: git -C sources/meta-compulab cherry-pick a999f3c92d8613f5f6c585bf729c46f101beae3f

* `mozjs fetch issue`
[source,console]
$: git -C sources/meta-compulab cherry-pick 2087d68cdfe29a0346f20952808145f818730fdb

### Build Procedure
#### Select an available machine: `cm-fx6-evk/cl-som-imx6ul/cl-som-imx7/cl-som-imx6`
[source,console]
$: export MACHINE=cm-fx6-evk
or
$: export MACHINE=cl-som-imx6ul
or
$: export MACHINE=cl-som-imx7
or
$: export MACHINE=cl-som-imx6

#### Select an available distro: `x11/fb/xwayland/wayland`
[source,console]
$: export DISTRO=fsl-imx-x11
or
$: export DISTRO=fsl-imx-fb
or
$: export DISTRO=fsl-imx-xwayland
or
$: export DISTRO=fsl-imx-wayland

#### Create Build Environment
* Issue `IMX Vendor` Setup Script
[source,console]
$: source fsl-setup-release.sh -b build-${MACHINE}-${DISTRO}

* Issue `CompuLab` Setup Script
[source,console]
$: source ../sources/meta-compulab/bb-tools/setup-compulab-env

#### Build Instruction
##### Select an available image: `fsl-image-gui/fsl-image-qt5/compulab-eval-image/compulab-eval-image-xfce`
[source,console]
$: export IMAGE=fsl-image-gui
or
$: export IMAGE=fsl-image-qt5
or
$: export IMAGE=compulab-eval-image
or
$: export IMAGE=compulab-eval-image-xfce

##### Build Evaluation Image
[source,console]
$: bitbake ${IMAGE}

##### Build kernel only
[source,console]
$: bitbake linux-compulab

##### Build U-Boot only
[source,console]
$: bitbake u-boot-compulab

## https://github.com/compulab-yokneam/Documentation/tree/master/common/post-build#post-build-instructions[Post Build Instructions]
