#!/bin/bash

be=${1:-"fb"}
declare -A backend=(["fb"]=1 ["x11"]=1 ["wl"]=1)
[[ ${backend[${be}]} -eq 1 ]] || exit 2

pushd . &>/dev/null
cd /usr/lib &>/dev/null

libEGL="libEGL.so libEGL.so.1 libEGL.so.1.0"
libGAL="libGAL.so"
libGLESv2="libGLESv2.so libGLESv2.so.2 libGLESv2.so.2.0.0"
libVDK="libVDK.so"
libvulkan="libvulkan.so"

for lib in libEGL libGAL libGLESv2 libVDK libvulkan;do
for l in ${!lib};do
ln -sf ${lib}-${be}.so ${l}
done
done

popd &>/dev/null
