# How to install BalenaOS on CompuLab iot-gate-imx8 devices.

* Assumption:
** All iot-gate-imx8 devices come with a pre-flased u-boot image.
** Installation media is a USB disk on key with a BalenaOS Live image.
** BalenaOS requiers a modified bootloader.

* BalenaOS Live image must have these mandatory packages:
** imx-boot
[source,code]
root@iot-gate-imx8:~# dpkg -L imx-boot
/.
/boot
/boot/imx-boot-iot-gate-imx8-sd.bin-flash_evk

** cl-uboot

** cl-deploy

** https://github.com/compulab-yokneam/meta-bsp-imx8mm/tree/iot-gate-imx8/recipes-bsp/u-boot-scr[u-boot-scr]

This script is in charge of updating the device bootloader if needed and booting the device up.
Here is the CompuLab https://github.com/compulab-yokneam/meta-bsp-imx8mm/blob/iot-gate-imx8/recipes-bsp/u-boot-scr/u-boot-script/iot-gate-imx8/boot.script[boot.scr implemetation]:

```
setenv nload ${loadaddr}
setenv oload ${fdt_addr}
setenv mmcdev 2
setenv mmcpart 1
setenv mmcoff 0x42
setenv bsize 0xB00
setenv bootloader ##BOOTLOADER##

# Load the new booloader from the file system
# 1) iface/dev/part defined by the default u-boot environment
# 2) the boot media second partition must have the device bootloader
# in the partition:boot directory
if load ${iface} ${dev}:2 ${nload} boot/${bootloader}
then

    # Read the current booloader from the boot device
    mmc dev ${mmcdev} ${mmcpart}
    mmc read ${oload} ${mmcoff} ${bsize}

    # Compare the old & the new one.
    if cmp.b ${nload} ${oload} ${filesize}
    then
        echo Nothing to update
    else
        echo Updating the bootloader on mmc [${mmcdev}:${mmcpart}]
        mmc write ${nload} ${mmcoff} ${bsize}
        mmc partconf ${mmcdev} 0 ${mmcpart} 0
        reset
    fi

else
    echo ##BOOTLOADER## file not found
fi

setenv script
boot
```

## BalenaOS image to the device internal storage:
Boot up an iot-gate-imx8 device from a USB media with a BalenaOS Live image.

While in Linux issue:

* Run cl-deploy
```
DST=/dev/mmcblk2 QUIET=Yes cl-deploy
```
Wait for a `SUCCESS` message.

* Power off the device
[source,code]
poweroff
* Remover the USB disk on key.
* Power on the device.

That is all.
