# How to install BalenaOS on the CompuLab iot-gate-imx8 device.

* Assumption:
All iot-gate-imx8 devices come with a pre-flased u-boot image.

* Installation media is an USB disk on key with a BalenaOS Live image.

* BalenaOS Live image must have these mandatory packages:
1) imx-boot
[source,code]
root@iot-gate-imx8:~# dpkg -L imx-boot
/.
/boot
/boot/imx-boot-iot-gate-imx8-sd.bin-flash_evk

2) cl-uboot
[source,code]
root@iot-gate-imx8:~# dpkg -L cl-uboot 
/usr 
/usr/local 
/usr/local/bin 
/usr/local/bin/cl-uboot 
/usr/local/bin/cl-uboot.work 
/usr/share 
/usr/share/applications 
/usr/share/applications/cl-uboot.desktop 
/usr/share/applications/cl-uboot.png

3) cl-deploy

4) A boot.scr at the 1-st media partition.
It is up to developers to provide the correct script contant. Here is just an empty template:
https://github.com/compulab-yokneam/meta-compulab-bsp/tree/master/meta-bsp/recipes-bsp/u-boot-scr

This script is in charge of updating the device bootloader if needed and booting the device up.
Here is a sample script:

```
setenv nload ${loadaddr}
setenv oload ${fdt_addr}
setenv mmcdev 2
setenv mmcpart 1
setenv mmcoff 0x42
setenv bsize 0xB00
setenv bootloader imx-boot-iot-gate-imx8-sd.bin-flash_evk

# Load a new booloader from the file system
load mmc ${bootdev} ${nload} ${bootloader}

# Read the current booloader from the boot device
mmc dev ${mmcdev} ${mmcpart}
mmc read ${oload} ${mmcoff} ${bsize}
if cmp.b ${nload} ${oload} ${filesize}
then
echo U-Boot versions match;
setenv script
boot
else
mmc write ${nload} ${mmcoff} ${bsize}
mmc partconf ${mmcdev} 0 ${mmcpart} 0
echo U-Boot updated finished
reset
fi
```
