# SIM7600

## ModemManager
The Debian `ModemManager` provides a wide range of commands for modem management.

* Get modem info
[source,code]
mmcli -m 0
  --------------------------------
  General  |            dbus path: /org/freedesktop/ModemManager1/Modem/0
           |            device id: 74f21510c20cf03751989d354235dddcf5e4d524
  --------------------------------
  Hardware |         manufacturer: QUALCOMM INCORPORATED
           |                model: 0
           |             revision: LE11B02SIM7500A
           |         h/w revision: 10000
           |            supported: gsm-umts, lte
           |              current: gsm-umts, lte
           |         equipment id: 868022030064831
  --------------------------------
  System   |               device: /sys/devices/platform/32e50000.usb/ci_hdrc.1/usb2/2-1/2-1.5
           |              drivers: option1, qmi_wwan
           |               plugin: SimTech
           |         primary port: cdc-wdm0
           |                ports: ttyUSB0 (qcdm), ttyUSB2 (at), cdc-wdm0 (qmi), wwan0 (net),
           |                       ttyUSB3 (at)
  --------------------------------
  Status   |                 lock: sim-pin2
           |       unlock retries: sim-pin (5), sim-pin2 (5), sim-puk (5), sim-puk2 (5)
           |                state: registered
           |          power state: on
           |          access tech: umts
           |       signal quality: 39% (cached)
  --------------------------------
  Modes    |            supported: allowed: 3g; preferred: none
           |                       allowed: 4g; preferred: none
           |                       allowed: 3g, 4g; preferred: 3g
           |                       allowed: 3g, 4g; preferred: 4g
           |              current: allowed: 3g, 4g; preferred: 4g
  --------------------------------
  Bands    |            supported: utran-5, utran-2, eutran-2, eutran-4, eutran-5, eutran-12
           |              current: utran-5, utran-2, eutran-2, eutran-4, eutran-12
  --------------------------------
  IP       |            supported: ipv4, ipv6, ipv4v6
  --------------------------------
  3GPP     |                 imei: 868022030064831
           |          operator id: 42503
           |         registration: home
  --------------------------------
  3GPP EPS | ue mode of operation: csps-1
  --------------------------------
  SIM      |            dbus path: /org/freedesktop/ModemManager1/SIM/0
  
## AT-Commands

|=====
|NOTE| 1) AT command mode works if a SIM card is installed. +
Issue this command `mmcli -m 0 -w` in order to get the modem state. +
2) AT command mode requires `debug` mode of the https://www.freedesktop.org/wiki/Software/ModemManager/Debugging/[ModemManager]
|=====

### Sending https://simcom.ee/documents/SIM7600C/SIM7500_SIM7600%20Series_AT%20Command%20Manual_V1.01.pdf[AT Commands]

* AT-Commands
** Request model information:
[source,code]
mmcli -m 0 --command='AT+CGMM'
response: 'SIMCOM_SIM7600A-H'

** Request revision indentification:
[source,code]
mmcli -m 0 --command='AT+CGMR'
response: '+CGMR: LE11B02SIM7500A'

** Request product serial number identification:
[source,code]
mmcli -m 0 --command='AT+CGSN'
response: '868022030064831'

## libqmi-utils

Another way to talk to QMI modems is to use the https://www.freedesktop.org/software/libqmi/man/latest/qmicli.1.html[QMI protocol from the command line].

* Usefull commands

** get-ids
[source,code]
qmicli -d /dev/cdc-wdm0 --dms-get-ids
[/dev/cdc-wdm0] Device IDs retrieved:
         ESN: '0'
        IMEI: '868022030064831'
        MEID: 'unknown'

** get-capabilities
[source,code]
qmicli -d /dev/cdc-wdm0 --dms-get-capabilities
[/dev/cdc-wdm0] Device capabilities retrieved:
        Max TX channel rate: '50000000'
        Max RX channel rate: '100000000'
               Data Service: 'non-simultaneous-cs-ps'
                        SIM: 'supported'
                   Networks: 'umts, lte'

** get-manufacturer
[source,code]
qmicli -d /dev/cdc-wdm0 --dms-get-manufacturer
[/dev/cdc-wdm0] Device manufacturer retrieved:
        Manufacturer: 'QUALCOMM INCORPORATED'

** get-model
[source,code]
qmicli -d /dev/cdc-wdm0 --dms-get-model
[/dev/cdc-wdm0] Device model retrieved:
        Model: '0'

** get-revision
[source,code]
qmicli -d /dev/cdc-wdm0 --dms-get-revision
[/dev/cdc-wdm0] Device revision retrieved:
        Revision: 'LE11B02SIM7500A'

** get-hardware-revision
[source,code]
qmicli -d /dev/cdc-wdm0  --dms-get-hardware-revision
[/dev/cdc-wdm0] Hardware revision retrieved:
        Revision: '10000'

** get-operating-mode
[source,code]
qmicli -d /dev/cdc-wdm0  --dms-get-operating-mode
[/dev/cdc-wdm0] Operating mode retrieved:
        Mode: 'online'
        HW restricted: 'no'

** band-capabilities
[source,code]
qmicli -d /dev/cdc-wdm0  --dms-get-band-capabilities
[/dev/cdc-wdm0] Device band capabilities retrieved:
        Bands: 'wcdma-pcs-1900, wcdma-850-us'
        LTE bands: '2, 4, 5, 12'

** get-system-info
[source,code]
qmicli -d /dev/cdc-wdm0 --nas-get-system-info
[/dev/cdc-wdm0] Successfully got system info:
        WCDMA service:
                Status: 'limited'
                True Status: 'limited'
                Preferred data path: 'no'
                Domain: 'none'
                Service capability: 'cs-ps'
                Roaming status: 'on'
                Forbidden: 'no'
                Location Area Code: '33941'
                Cell ID: '6192238'
                MCC: '425'
                MNC: '02'
                HS call status: 'hsdpa-hsupa-unsupported'
                HS service: 'hsdpa-hsupa-supported'
                Primary scrambling code: '11'
                Cell broadcast support: 'on'
                Call barring status (CS): 'emergency-only'
                Call barring status (PS): 'emergency-only'
                Cipher Domain: 'none'
        LTE service:
                Status: 'none'
                True Status: 'none'
                Preferred data path: 'no'
        SIM reject info: 'unavailable'

** get-serving-system
[source,code]
qmicli -d /dev/cdc-wdm0  --nas-get-serving-system
[/dev/cdc-wdm0] Successfully got serving system:
        Registration state: 'not-registered-searching'
        CS: 'detached'
        PS: 'detached'
        Selected network: '3gpp'
        Radio interfaces: '1'
                [0]: 'umts'
        Roaming status: 'on'
        Data service capabilities: '0'
        Current PLMN:
                MCC: '425'
                MNC: '2'
                Description: ''
        Roaming indicators: '1'
                [0]: 'on' (umts)
        Detailed status:
                Status: 'limited'
                Capability: 'cs-ps'
                HDR Status: 'none'
                HDR Hybrid: 'no'
                Forbidden: 'no'
        UMTS primary scrambling code: '11'
        Full operator code info:
                MCC: '425'
                MNC: '2'
                MNC with PCS digit: 'no'

** get-system-selection-preference
[source,code]
qmicli -d /dev/cdc-wdm0  --nas-get-system-selection-preference
[/dev/cdc-wdm0] Successfully got system selection preference
        Emergency mode: 'no'
        Mode preference: 'umts, lte'
        Band preference: 'wcdma-pcs-1900, wcdma-850-us'
        LTE band preference: '2, 4, 12'
        TD-SCDMA band preference: 'a, b, c, d, e, f'
        Roaming preference: 'any'
        Network selection preference: 'automatic'
        Service domain preference: 'cs-ps'
        GSM/WCDMA acquisition order preference: 'automatic'
        Acquisition order preference: lte, umts, gsm, cdma-1x, cdma-1xevdo

** network-scan
[source,code]
qmicli -d /dev/cdc-wdm0  --nas-network-scan
[/dev/cdc-wdm0] Successfully scanned networks
Network [0]:
        MCC: '425'
        MNC: '3'
        Status: 'available, roaming, not-forbidden, not-preferred'
        Description: 'PCL'
Network [1]:
        MCC: '425'
        MNC: '8'
        Status: 'available, roaming, not-forbidden, not-preferred'
        Description: '425 08'
Network [2]:
        MCC: '425'
        MNC: '2'
        Status: 'available, roaming, not-forbidden, not-preferred'
        Description: 'Cellcom'
Network [0]:
        MCC: '425'
        MNC: '3'
        RAT: 'umts'
Network [1]:
        MCC: '425'
        MNC: '8'
        RAT: 'umts'
Network [2]:
        MCC: '425'
        MNC: '2'
        RAT: 'umts'
Network [0]:
        MCC: '425'
        MNC: '3'
        MCC with PCS digit: 'no'
Network [1]:
        MCC: '425'
        MNC: '8'
        MCC with PCS digit: 'no'
Network [2]:
        MCC: '425'
        MNC: '2'
        MCC with PCS digit: 'no'
